### ISSUE TITLE
Share Post copying title instead of URL

### ISSUE THREAD

**Issue by DanielFatkic** [InvisionPowerServices/Mobile-App-Issues#12]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

- [X] iOS
- [ ] Android

## Problem

The recently added share feature is copying following to the clipboard instead of the expected url 

> sadams101's post in "Google's New Nofollow, UGC and Sponsored Tags" at Invision Community

## Steps to reproduce

1. While viewing a post, tap on the 3 points and use the share feature 
2. copy it to the clipboard

**Comment by rikkitissier** [comment]
The Share option doesn't just copy the URL - it provides the description of what's being copied too (that's required when sharing on iOS). The Copy Permalink option I added earlier hasn't yet been published, but that will copy just the URL. I'll try and get that published tomorrow.

**Comment by DanielFatkic** [comment]
Thx, makes sense now
