### ISSUE TITLE
Numbers aren't formatted with thousands separators

### ISSUE THREAD

**Issue by jackwickham** [InvisionPowerServices/Mobile-App-Issues#14]
## Platform

Which platform do you use?

- [ ] iOS
- [x] Android

## Which feature/screen does this feedback concern?
The number formats - first noticed in the list of subforums, but I think it seems to be everywhere numbers are displayed.

## What's your feedback?
Numbers are displayed without any thousands separators, so Feedback and Ideas shows "163982 posts" rather than "163,982 posts", making it hard to read and not look great.

**Comment by rikkitissier** [comment]
Hmmm, seems toLocaleString isn't supported in the JS engine shipped with RN on Android... that sucks. Will try and find a solution.
