### ISSUE TITLE
"Forums" link is placed in super-inconvenient place

### ISSUE THREAD

**Issue by Veratyr** [InvisionPowerServices/Mobile-App-Issues#19]
## Platform

- Android

## Which feature/screen does this feedback concern?

Frequently used links to apps/topics(see screenshot below)

## What's your feedback?

I think this links should be available on the bottom, as they will be used frequently and should be available as near as possible including the case when large phone is used with one hand.

Actually this links was the first thing i've looked for after launched app and i was a bit disappointed because:

1. It took some time to find them
2. They were not available under my thumb
3. They are available only from "Home" and can't be quickly accessed from any other screen.

![IMG_20190929_170329](https://user-images.githubusercontent.com/2811248/65833763-4df38c00-e2dc-11e9-90da-d679b088baef.jpg)

I hope you'll fix that. Thank you!

**Comment by rikkitissier** [comment]
It may seem like an odd choice while the app is primarily forum-focused right now - but we're looking forwards to when other apps are supported. Forums isn't really any more 'special' than the other apps, so shouldn't necessarily have a place on the main tab bar.

Right now this is intended, but we'll keep an eye on further feedback :)

**Comment by Veratyr** [comment]
Yes, i know what you have plans to support all other apps in future, but still prefer to have this links right under the thumb. I hope you'll consider moving it to the bottom, or if you need i could make some mockups and show how it could fit there even when blogs/clubs/gallery etc will be also available in the app.
