### ISSUE TITLE
Reading Blog entries

### ISSUE THREAD

**Issue by lorenjcook** [InvisionPowerServices/Mobile-App-Issues#20]
_Please use this issue only for specific feedback or ideas about particular features/screens. If you would like to share more general feedback about the app, please email mobilesupport@invisionpower.com_

_We'll respond to each piece of feedback, but may not address all feedback immedately. Feedback may be closed and moved to our private tracker for internal discussion._

## Platform

Which platform do you use?

- [ ] iOS
- [ x] Android

## Which feature/screen does this feedback concern?
Blogs
## What's your feedback?
After reading a blog entry using the Android back arrow returns you to the Home page not to the Blog home.

**Comment by rikkitissier** [comment]
Could you let me know the navigation steps you're doing here? This is what I've done and it works as expected:

- From the home screen, tap a blog entry in Our Picks
- Webview loads and shows blog entry
- Tap hardware back button
- I'm returned to the home screen

**Comment by lorenjcook** [comment]
Sorry, for the delay I was out all day today.

Choose Our Blog from the app top menu
Scroll down and open a blog posting
Tap hardware back button

This happens on some blog entries and not others (odd).
On some blog entries, it takes back to the app Home page while on others it does (what I believe to be correct) and takes you back to the blog home.

Android 10 on Google Pixel 3a XL.
