### ISSUE TITLE
Code is not formatted correctly

### ISSUE THREAD

**Issue by jackwickham** [InvisionPowerServices/Mobile-App-Issues#21]
## Platform

- Android

## Problem
Code is formatted without line breaks. There's also no syntax highlighting.

## Steps to reproduce

1. View a topic with a code tag that contains multiple lines of code
2. See that the code all runs into one

## Screenshot

In the app:
![App with code lines running togther](https://user-images.githubusercontent.com/8701337/65839946-48149f80-e30a-11e9-82c5-dc10b3de50c3.png)
In the mobile browser:
![image](https://user-images.githubusercontent.com/8701337/65839959-68dcf500-e30a-11e9-80ad-28e04e9f37dd.png)

**Comment by rikkitissier** [comment]
Highlighting won't be supported yet but spacing should be fixed.
