### ISSUE TITLE
iOS 13.1.2 missing language string

### ISSUE THREAD

**Issue by The-Heff** [InvisionPowerServices/Mobile-App-Issues#22]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

- iOS 13.1.2

## Problem

There is a missing language string on the legal notices menu.

## Steps to reproduce

1. Open legal notices menu

## Screenshot

![A8D9DDBD-1771-4CC5-8005-B6B145E8EB30](https://user-images.githubusercontent.com/55706827/66035108-73fa7580-e502-11e9-9acd-520db1ed9f2f.png)

**Comment by rikkitissier** [comment]
This happens when our site hasn't been updated just yet. Should be fixed once we're on 4.4.7 :)
