### ISSUE TITLE
iOS 13.1.2 Memoji not posting

### ISSUE THREAD

**Issue by The-Heff** [InvisionPowerServices/Mobile-App-Issues#27]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

- iOS 13.1.2

## Problem

iOS 13 supports customisable emoji, “Memoji”, which when used resulted in a large blank placeholder. See my test post in the test area.

## Steps to reproduce

1. Use iOS 13
2. Post a Memoji

## Screenshot

![840C3487-3847-47FC-9F68-918770C9174D](https://user-images.githubusercontent.com/55706827/66111415-b97d7800-e5c0-11e9-84b1-c7aa5a9caa25.png)

**Comment by rikkitissier** [comment]
I can't find any info about disabling this option in the keyboard, so until we support uploading by pasting, unfortunately we'll have to live with this issue.
