### ISSUE TITLE
Blog is a web view?

### ISSUE THREAD

**Issue by alexwebsites** [InvisionPowerServices/Mobile-App-Issues#28]
_Please use this issue only for specific feedback or ideas about particular features/screens. If you would like to share more general feedback about the app, please email mobilesupport@invisionpower.com_

_We'll respond to each piece of feedback, but may not address all feedback immedately. Feedback may be closed and moved to our private tracker for internal discussion._

## Platform

Which platform do you use?

- [x ] iOS
- [ ] Android

## Which feature/screen does this feedback concern?

Blogs

## What's your feedback?

Blogs opens to a web view and I am not logged in, is this the way it’s designed?

**Comment by rikkitissier** [comment]
They do open in a webview, but if you're logged into the app you should be logged into the page in the webview too. Is that not the case? I just tested it and it appears to be working for me.

**Comment by alexwebsites** [comment]
Correct, logged into the app but going to blogs I am not logged in. Drop the menu down I can go to the login page. I logged in and now it’s ok and can comment. 

Logged out of app but still logged in to blogs web view. Not syncing login/logout.

**Comment by alexwebsites** [comment]
I logged out of the app and returned to using it this evening. Logged in through the app and first attempt didn’t log me into the app. Tried again and logged in. Went to visit blogs and found I am not logged in.

**Comment by rikkitissier** [comment]
This should now be fixed.
