### ISSUE TITLE
Forums and All topics opened to a web view

### ISSUE THREAD

**Issue by alexwebsites** [InvisionPowerServices/Mobile-App-Issues#29]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

- [x ] iOS
- [ ] Android

## Problem

_Enter a short description of the problem. What did you expect to happen? What actually happens? Were there any error messages?_

No error message. Opened the app from last using 10 hours ago. Forums and all topics links opened to a web view. I closed the app and reopened and it seemed to now work through the app. Tried again and seems ok. 

## Steps to reproduce

1. 
2.
3. etc.

## Screenshot

_Please add a screenshot and/or video to illustrate the problem. You can paste images right from your clipboard into this textbox to attach them to this issue._

**Comment by rikkitissier** [comment]
I was working on URL detection yesterday and I think I probably published something that wasn't working right. Sounds like it worked ok for you in the end, and I'm not able to reproduce it now.
