### ISSUE TITLE
iOS 12.4.1 Dark mode on Pages not working

### ISSUE THREAD

**Issue by The-Heff** [InvisionPowerServices/Mobile-App-Issues#3]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

iOS 12.4.1

## Problem

When in dark mode, clicking on links to articles (assume Pages app?) loads in the light theme rather than dark.

## Steps to reproduce

1. Enable dark mode
2. Open the article posted by Rikki about the app

## Screenshot

![0F7E8428-39B3-4071-85F7-A68B81177A20](https://user-images.githubusercontent.com/55706827/65441962-40915a00-de23-11e9-801a-1622db8ae948.png)
![8EA3CDB4-17DA-40E9-8B1C-5063F57D5EA6](https://user-images.githubusercontent.com/55706827/65441963-40915a00-de23-11e9-96d5-f67e11b5b86c.png)

**Comment by rikkitissier** [comment]
This is a limitation right now - dark mode won't apply to content shown in a web view (i.e. pages actually coming from the website, versus created inside the app). As more areas are supported in the app natively, there should be fewer cases of this happening.
