### ISSUE TITLE
Notifications count on app icon

### ISSUE THREAD

**Issue by alexwebsites** [InvisionPowerServices/Mobile-App-Issues#30]
_Please use this issue only for specific feedback or ideas about particular features/screens. If you would like to share more general feedback about the app, please email mobilesupport@invisionpower.com_

_We'll respond to each piece of feedback, but may not address all feedback immedately. Feedback may be closed and moved to our private tracker for internal discussion._

## Platform

Which platform do you use?

- [x] iOS
- [ ] Android

## Which feature/screen does this feedback concern?

Notifications 

## What's your feedback?

Would be nice to have a notification count in red on the actual app icon in iOS like other apps do.

**Comment by rikkitissier** [comment]
We may be able to do this for white-label apps, but I don't think it'll be possible for the main multi-community app. The reason is the badge count is sent with push notifications, and since notifications will be coming from multiple communities we won't have a way to know the total across all communities.

**Comment by rikkitissier** [comment]
@mark-wade Tagging you for thoughts on this too.

**Comment by mark-wade** [comment]
I think it should be possible. When we send a notification, the community can send with that the number of unread notifications. We can then just total these up and when the user opens the app ping each community the user is registered to to ask for an updated count.

It means if a user has been reading notifications on the web, their badge will be inaccurate but that's pretty common to all apps: if I read a Facebook message on my laptop for example, the badge just disappears when I open the app.

**Comment by rikkitissier** [comment]
We're discussing this internally to decide whether it's something we'd be able to do at a technical level :)
