### ISSUE TITLE
Can't scroll to the bottom of the reply editor

### ISSUE THREAD

**Issue by jackwickham** [InvisionPowerServices/Mobile-App-Issues#32]
## Platform

- Android

## Problem

Scrolling the editor is really janky on android. When the keyboard is showing, you can't scroll all the way to the bottom, so some of the text is hidden behind the keboard.
![image](https://user-images.githubusercontent.com/8701337/66266869-be416680-e822-11e9-8684-cac75befe3c7.png)

When the keyboard is not showing, sometimes the formatting toolbar stays where it is, in which case it still covers up some of the text, except a sliver that appears underneath it (no screenshot for this because I couldn't reproduce it on demand). Other times, the editor just takes up the top ⅔ of the screen, and there is a blank bar at the bottom of the editor in the same colour as the editor that makes it look like you are at the bottom when you aren't.
![image](https://user-images.githubusercontent.com/8701337/66266873-c7cace80-e822-11e9-927a-3c815f7f916c.png)

**Comment by rikkitissier** [comment]
Related: https://github.com/InvisionPowerServices/Mobile-App-Issues/issues/26
