### ISSUE TITLE
The whole block should be tappable in forum listing

### ISSUE THREAD

**Issue by jackwickham** [InvisionPowerServices/Mobile-App-Issues#34]
## Platform

- Android

## Which feature/screen does this feedback concern?
The list of forums, and the list of topics within the forum.

## What's your feedback?
The linked part of the forum/topic items is just the title. This seems unintuitive to me - at least on Android, the tap area would usually be the entire block. This results in it sometimes feeling like it's just broken.

**Comment by rikkitissier** [comment]
I cannot reproduce this nor does it match up with how the list is constructed. Which device are you using, and does this happen every time you use the app or was it a one-off thing?

**Comment by jackwickham** [comment]
I did think that it was not registering, but it's possible that it was just being very slow to change pages (per my feedback email earlier). I have just checked and it does in fact seem to be working (slowly).
