### ISSUE TITLE
Dark theme missing styling

### ISSUE THREAD

**Issue by jackwickham** [InvisionPowerServices/Mobile-App-Issues#35]
## Platform

- Android

## Problem

I've noticed that there isn't dark theme styling:
* On the "Create new topic" button when viewing a forum
* On the editor control
* On the (very iOS-looking) post options dialog
* On the (i) icon when reporting a post (it's black against a dark background)
* On the background of the "Submit Report" button
* On the "Write a reply" placeholder (although that one may be a design choice, and could be left as it is)
* On the "Past hour"/etc bits when viewing a stream

**Comment by rikkitissier** [comment]
Some of these are intended (they are dark on the regular theme, so 'reversed' on the dark theme). There are a couple of accidental ones that I'll fix up though.

**Comment by jackwickham** [comment]
Sounds good, although in my experience of developing a dark theme I would suggest not making things light _just_ because they were dark on the light theme. Light elements on a dark theme stand out a lot more than dark elements on a light theme.

**Comment by rikkitissier** [comment]
I've fixed the obviously-incorrect ones. I think your feedback is fair about light on dark being much more prominent, so I'm going to consider that more and may make changes to the Create Topic button, stream headers etc.
