### ISSUE TITLE
Tapping on a status update opens a random member profile

### ISSUE THREAD

**Issue by jackwickham** [InvisionPowerServices/Mobile-App-Issues#40]
## Platform
- Android

## Problem

If you tap on a status update, such as when viewing a member's content or an activity feed, it takes you to an unrelated member's profile. I presume, although have not checked, that the profile that you are taken to is that of the member with the same ID as the status update.

## Steps to reproduce

1. Tap on a status update
2. Observe that you become lost

Also, for some reason the Guest member is listed as having joined on 10/06/2019 (assuming the dates are locale formatted, that's 10 June 2019).

There's also currently no way to post status updates, so I'm curious as to whether that's planned.

**Comment by rikkitissier** [comment]
> There's also currently no way to post status updates, so I'm curious as to whether that's planned.

The aim is to, in time, support all functionality. That said, status updates don't see a ton of use across client communities, so it likely won't be a priority.
