### ISSUE TITLE
iOS 13.1.2 actioning a push notification should mark it as read/completed

### ISSUE THREAD

**Issue by The-Heff** [InvisionPowerServices/Mobile-App-Issues#43]
## Platform

Which platform do you use?

- iOS 13.1.2

## Which feature/screen does this feedback concern?

Notifications.

## What's your feedback?

When push notifications are received and clicked on, either from the notification centre or from the lock screen, the notification in the app remains "unread", requiring an extra set of actions to dismiss it. In essence, you have to read something _twice_ in order to dismiss the notification. It would be better if actioning a push notification also marked the corresponding in-app notification as completed too.

**Comment by rikkitissier** [comment]
@mark-wade This is a good point... do you think it's technically feasible? I guess we'd need to send the community notification ID with the push notification, and then have the app send a mutation with that ID.

Having said that, is this how apps work in general? I watch more closely when I use Facebook/Twitter next and make sure it's consistent with those.

**Comment by rikkitissier** [comment]
OK yeah, Facebook works like that.

**Comment by mark-wade** [comment]
I think so yeah. I'll put together the backends for it

**Comment by mark-wade** [comment]
@rikkitissier I have made it so now when the app receives a push notification there is an `unreadCount` property in the notification's data which includes a count. I have pushed the required code change to our community too.

You will need to:

1. Keep a record of these counts for each of the communities the user has added to the app
2. When the user opens the app, ping each of the communities they have added to the app to update the count. This is actually already available in the GraphQL API: the `notificationCount` field in the `MemberType`.
3. Update the count whenever the user does something in a community which will cause the notification to be marked as read, by reading that same property.
4. Show the total of these as a badge

Do you need anything else from me?

**Comment by rikkitissier** [comment]
@mark-wade This is actually quite a bit more complex than that I think; for a start, the badge count is sent with the push notification, it's not set by the app itself. I'll get with you privately so we can discuss how we might implement both this and https://github.com/InvisionPowerServices/Mobile-App-Issues/issues/30.

**Comment by mark-wade** [comment]
Sounds good. I think my above comment was meant to be on #30.

**Comment by rikkitissier** [comment]
We're discussing this internally to decide whether it's something we'd be able to do at a technical level :)
