### ISSUE TITLE
Email notifications not working with app

### ISSUE THREAD

**Issue by alexwebsites** [InvisionPowerServices/Mobile-App-Issues#45]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

- [x ] iOS
- [ ] Android

## Problem

_Enter a short description of the problem. What did you expect to happen? What actually happens? Were there any error messages?_

Email Notifications are not working although notifications are set to app and email. App notifications are working. They were working fine before app notifications were changed to include app by me. Looked at settings and both types are still enabled. 

## Steps to reproduce

1.
2.
3. etc.

## Screenshot

_Please add a screenshot and/or video to illustrate the problem. You can paste images right from your clipboard into this textbox to attach them to this issue._

**Comment by rikkitissier** [comment]
@mark-wade Tagging you on this one, though they are working fine for me.

**Comment by alexwebsites** [comment]
I may be wrong guys, just noticed two notification emails I was missing in my junk folder. Don’t chase it, might be on my end. Apologies for reporting because wasn’t having issues receiving email to my own domain before. I’m checking all my spam/junk settings.

**Comment by rikkitissier** [comment]
OK, in that case I'll close this out - I'm receiving email notifications and haven't had any other reports from the IPS team (we've been using the app for a few months so would have likely spotted it!).
