### ISSUE TITLE
iOS 13.1.2 I can see hidden content

### ISSUE THREAD

**Issue by The-Heff** [InvisionPowerServices/Mobile-App-Issues#46]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

- iOS 13.1.2

## Problem

I can see hidden content in thread which is not visible on the web.

## Steps to reproduce

1. Log in as a non-moderator
2. Check this thread: https://invisioncommunity.com/forums/topic/454269-automatically-enlarge-emojis-if-on-their-own-line/

## Screenshot

![7DEFA018-B4D2-4BDA-9C93-39EA86501E2B](https://user-images.githubusercontent.com/55706827/66527186-13b39700-eaf3-11e9-9ded-5c98c2162aca.png)

**Comment by rikkitissier** [comment]
Thanks - fixed.
