### ISSUE TITLE
iOS 13.1.2 Inserting links fails

### ISSUE THREAD

**Issue by The-Heff** [InvisionPowerServices/Mobile-App-Issues#47]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

- iOS 13.1.2

## Problem

When composing a post, links could not be inserted.

## Steps to reproduce

1. Crest a post
2. Attempt to insert a link

## Screenshot

![A9DF67C9-8188-40D8-86C7-18904C72AA32](https://user-images.githubusercontent.com/55706827/66783402-bdb66900-eecf-11e9-84b2-555f1239da46.png)
![9101BAC3-953A-4AB7-A574-85A1E1D3B616](https://user-images.githubusercontent.com/55706827/66783403-bdb66900-eecf-11e9-947b-d5bf8226a2b9.png)
![0353ED30-795F-4D96-848B-999FBDD20FDE](https://user-images.githubusercontent.com/55706827/66783406-bdb66900-eecf-11e9-9316-024b7015b740.png)

**Comment by rikkitissier** [comment]
Interesting... links actually need http(s):// to be valid, and if it's invalid you should get an alert. But it looks like if you start it www. it doesn't show the error 🧐
