### ISSUE TITLE
Cannot use GIF while posting

### ISSUE THREAD

**Issue by SonyaAsterisk** [InvisionPowerServices/Mobile-App-Issues#58]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

- [ ] iOS
- [ x
![Screenshot_20191124-101601_Invision Community](https://user-images.githubusercontent.com/22191765/69492483-b3f72c80-0ea3-11ea-802b-86c7694fcfe1.jpg)
] Android

## Problem

Using GIF is not possible. There is an error in German (OS language) "This content cannot be entered."

## Steps to reproduce

1. Try to create new post.
2. Select GIF beside emojis
3. Tap on any GIF to add it to the content.
4. The error (s. screenshot) appears.

## Screenshot

_Please add a screenshot and/or video to illustrate the problem. You can paste images right from your clipboard into this textbox to attach them to this issue._

**Comment by rikkitissier** [comment]
This won't be supported right now, and unfortunately I don't think I have a way of disabling that option in the keyboard. This should be solved once we support inline images in future, though.
