### ISSUE TITLE
iOS 12.4.1 spell checking / autocorrect issues

### ISSUE THREAD

**Issue by The-Heff** [InvisionPowerServices/Mobile-App-Issues#7]
## Platform

Which platform do you use? No need to try reproducing the issue on both platforms; just let us know which one you use and we'll test from there.

- iOS 12.4.1

## Problem

When using formatting tools over multiple lines, autocorrect got confused and treated the typed text as one long word.

## Steps to reproduce

1. Select a format, e.g. bold
2. Type a word
3. Press enter
4. Continue typing

## Screenshot

![EE963D99-C20C-4CE5-80FC-6817B8360308](https://user-images.githubusercontent.com/55706827/65504014-0de86f80-debe-11e9-9f3d-776475a9a1db.png)

**Comment by rikkitissier** [comment]
Like the other issue, this is unfortunately handled by iOS :/
